In [1]:
import pandas as pd
import sqlalchemy

#### SQLite to create a DB

The next cell creates an association with an SQLite database named 'tech_ceo_info.db' in the current directory. When I executed the command, 'tech_ceo_info.db' did not exist, so it was created without any relations (tables).

In [2]:
db = sqlalchemy.create_engine('sqlite:///tech_ceo_info.db')

In the following cell, I use pandas to create a dataframe representing our the performance of various CEOs in our degree programs data (fictitious).

In [3]:
dep_data = pd.DataFrame({
    "name": ["Sergey Brin", "Danah Boyd", "Bill Gates", "Hillary Mason", "Mike Olson", "Mark Zuckerburg", "Sheryl Sandberg", "Susan Wojcicki", "Marissa Mayer"],
    "gpa": [2.8, 3.9, 1, 4, 3.7, 3.8, 3.6, 3.8, 2.6],
    "age": [45, 40, 63, 39, 53, 34, 49, 50, 43],
    "dept": ["CS", "CS", "CS", "DATASCI", "CS", "CS", "BUSINESS", "BUSINESS", "BUSINESS"]
})

In [4]:
dep_data

              name  gpa  age      dept
0      Sergey Brin  2.8   45        CS
1       Danah Boyd  3.9   40        CS
2       Bill Gates  1.0   63        CS
3    Hillary Mason  4.0   39   DATASCI
4       Mike Olson  3.7   53        CS
5  Mark Zuckerburg  3.8   34        CS
6  Sheryl Sandberg  3.6   49  BUSINESS
7   Susan Wojcicki  3.8   50  BUSINESS
8    Marissa Mayer  2.6   43  BUSINESS

Now I create another Dataframe of the net worths for each tech giant (not ficticious).

In [5]:
net_worth = pd.DataFrame({
    "name": ["Sergey Brin", "Danah Boyd", "Bill Gates", "Hillary Mason", "Mike Olson", "Mark Zuckerburg", "Sheryl Sandberg", "Susan Wojcicki", "Marissa Mayer"],
    "net_worth_millions": [82200, 6, 1100, None, 61, 48400, 15000, 765, 600]
})

In [6]:
net_worth

              name  net_worth_millions
0      Sergey Brin             82200.0
1       Danah Boyd                 6.0
2       Bill Gates              1100.0
3    Hillary Mason                 NaN
4       Mike Olson                61.0
5  Mark Zuckerburg             48400.0
6  Sheryl Sandberg             15000.0
7   Susan Wojcicki               765.0
8    Marissa Mayer               600.0

Now write both of our tables into the database.

In [7]:
dep_data.to_sql('dep_gpa_data', db)

9

In [8]:
net_worth.to_sql('tech_ceo_net_worth', db)

9